dist: trusty
language: node_js
node_js:
- 8.2.0

branches:
  only:
  - master
  - develop
  - "/^greenkeeper\\/.*$/"

before_install:
- npm i -g greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update
- npm run snapshot
script:
- npm run test-ci
after_success:
- npm run report-coverage
- greenkeeper-lockfile-upload
