dist: trusty
services:
  - docker
language: node_js
node_js:
- 8.1.4

branches:
  only:
  - master
  - develop
  - "/^greenkeeper\\/.*$/"

before_install:
- npm i -g greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update
- npm run snapshot
script:
- npm run test-ci
after_success:
- npm run report-coverage
- greenkeeper-lockfile-upload

before_deploy:
- ./deploy/ecs-install-cli.sh
deploy:
  provider: script
  script: node ./deploy/ecs-deploy.js
  on:
    branch: develop
after_deploy:
- ./deploy/opbeat-report-deploy.sh
