version: '2'
services:
  app-server:
    image: "${APP_SERVER_IMAGE}"
    environment:
      PORT: 3000
      NODE_ENV: production
    # We expose the server port to an unspecified destination port so that
    # multiple app servers can be on the same container host. The ALB
    # "target group" registration handles directing traffic to the right
    # container.
    ports:
     - "3000"
    # 200mb in bytes
    mem_reservation: 209715200
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_DEFAULT_REGION}"
        awslogs-group: "${AWS_CLOUDWATCH_LOGS_GROUP}"
        awslogs-stream-prefix: "${AWS_CLOUDWATCH_LOGS_PREFIX}"
