version: '2'
services:
  app-server:
    image: "${APP_SERVER_IMAGE}"
    environment:
      PORT: "${APP_SERVER_PORT}"
      NODE_ENV: production
      # Used by script/entrypoint.sh to download our .env configuration
      AWS_S3_CONFIG_URL: "${AWS_S3_CONFIG_URL}"
    # We expose the server port to an unspecified destination port so that
    # multiple app servers can be on the same container host. The ALB
    # "target group" registration handles directing traffic to the right
    # container.
    ports:
     - "${APP_SERVER_PORT}"
    mem_reservation: 209715200 # 200mb in bytes
    mem_limit: 524288000 # 500mb in bytes
    logging:
      driver: awslogs
      options:
        awslogs-region: "${AWS_DEFAULT_REGION}"
        awslogs-group: "${AWS_CLOUDWATCH_LOGS_GROUP}"
        awslogs-stream-prefix: "${AWS_CLOUDWATCH_LOGS_PREFIX}"
